{
    "name": "Community IoT Printing",
    "summary": "Print any Odoo PDF report through IoT Box Community.",
    "version": "19.0.1.0.0",
    "category": "Technical/IoT",
    "author": "JDA SOLUTIONS",
    "maintainer": "JDA SOLUTIONS",
    "website": "https://github.com/julesprog963-stack/community_iot_printing",
    "support": "julesprog963@gmail.com",
    "license": "LGPL-3",
    "price": 0.0,
    "currency": "USD",
    "images": [
        "static/description/main_screenshot.gif",
        "static/description/main_screenshot.png",
        "static/description/images/iot_print_menu.png",
        "static/description/images/iot_print_wizard.png",
        "static/description/images/iot_print_wizard_odoo19.png",
    ],
    "depends": ["base", "web", "community_iot_box"],
    "data": [
        "security/community_iot_printing_security.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "wizard/community_iot_print_wizard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "community_iot_printing/static/src/js/iot_action_menus.js",
            "community_iot_printing/static/src/xml/iot_action_menus.xml",
        ],
    },
    "application": False,
    "installable": True,
}
