LogLevel warn
MaxLogSize 0
Port 631
Listen 0.0.0.0:631
Browsing No
WebInterface No
DefaultAuthType None

<Location />
  Order allow,deny
  Allow all
</Location>

<Location /admin>
  Order allow,deny
  Allow all
</Location>

<Location /admin/conf>
  Order allow,deny
  Allow all
</Location>

<Policy default>
  <Limit Create-Job Print-Job Print-URI Validate-Job>
    Order allow,deny
    Allow all
  </Limit>
  <Limit Send-Document Send-URI Cancel-Job Cancel-My-Jobs Close-Job CUPS-Get-Document>
    AuthType None
    Order allow,deny
    Allow all
  </Limit>
  <Limit Pause-Printer Resume-Printer Set-Printer-Attributes>
    AuthType Basic
    Require user @SYSTEM
    Order allow,deny
    Allow all
  </Limit>
  <Limit CUPS-Add-Modify-Printer CUPS-Delete-Printer CUPS-Add-Modify-Class CUPS-Delete-Class CUPS-Set-Default>
    AuthType None
    Order allow,deny
    Allow all
  </Limit>
  <Limit All>
    Order deny,allow
  </Limit>
</Policy>
